# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20180223_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
